### ISSUE TITLE
mistakes

### ISSUE THREAD

**Issue by Nakasu-ksm** [amrit-das/Custom-Model-Training-PyTorch#5]
Traceback (most recent call last):
  File "predict.py", line 14, in <module>
    num_class = class_mapping(index=-1)
NameError: name 'class_mapping' is not defined
please help me thanks

**Comment by amrit-das** [comment]
Hey there sorry I forgot to update that part. Will do it ASAP

**Comment by amrit-das** [comment]
@wenshitao  Updated it, Please let me know if any other help/changes required
